services:
  app:
    build: 
      context: .
      args:
        BUILDPLATFORM: linux/arm64
    platform: linux/arm64
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app
      - /app/node_modules